DROP TABLE IF EXISTS Enemy;
CREATE TABLE IF NOT EXISTS Enemy (ID INTEGER PRIMARY KEY, HP INTEGER, NAME TEXT);
INSERT INTO Enemy (ID, HP, NAME) VALUES (1, 10, 'TEST ENEMY');

DROP TABLE IF EXISTS Ally;
CREATE TABLE IF NOT EXISTS Ally (ID INTEGER PRIMARY KEY, HP INTEGER, NAME TEXT);
INSERT INTO Ally (ID, HP, NAME) VALUES (1, 10, 'TEST ALLY');